### ISSUE TITLE
yarn failures

### ISSUE THREAD

**Issue by punkdit** [errorcorrectionzoo/eczoo_sitegen#1]
"yarn preview" fails with error:

Usage Error: Couldn't find a script named "preview".

"yarn build" fails with error:

Failed to initialize the SVG code graph exporter!

**Comment by valbert4** [comment]
@phfaist

**Comment by punkdit** [comment]
Just trying to compile eczoo on my local machine here...

**Comment by phfaist** [comment]
It's hard to guess what's wrong without any additional information. It works on my end.

Some things that come to mind:
- Are you in the right folder? You should be immediately in the root eczoo_sitegen/ folder.
- Try "less package.json". Do you see the "scripts" key and a "preview" in there? If not, you're probably in the wrong folder.
- You can also look up some basics of how to use yarn scripts - https://classic.yarnpkg.com/lang/en/docs/cli/run/

**Comment by punkdit** [comment]
Ok, the docs at https://github.com/errorcorrectionzoo/eczoo_sitegen need fixing, it says there

> cd eczoo_sitegen/site
> yarn preview

**Comment by phfaist** [comment]
Ah sorry, thanks for point it out.
